### ISSUE TITLE
No way to remove deployment in "cleanup failed" state

### ISSUE THREAD

**Issue by Alex-Sizov** [typeable/octopod#150]
If cleanup script has failed in non recoverable fashion and deployment got to the 'cleanup failed' state there is not way to delete it.
There must be --force flag in the cleanup command, which will delete all traces of deployment from database ignoring exit code from cleanup control script

**Comment by ilyakooo0** [comment]
`octo cleanup --force` would imply that there is some cleanup being performed. I e it should behave like `octo cleanup`, but disregarding some checks. This would be misleading since after we manually cleaned up a broken deployment we do not want to run cleanup scripts again.

For this reason, in #157 I introduced a separate command `octo delete` which just deletes a deployment from Octopod without doing anything else.
